name: Jira AI Summary

on:
  push:
    branches: ['**']  # Trigger on all branches

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full git history for diffs
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install --save-dev @types/node tsx
      
      - name: Parse commits and generate data
        run: |
          npx tsx .github/scripts/parse-commits.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}