name: PR Code Review

on:
  pull_request:
    types: [opened, edited, synchronize]
  issue_comment:
    types: [created]

jobs:
  code-review:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[review]')) ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.body == '/review')
    permissions:
      pull-requests: write # To add review comments
      contents: read       # To read PR files and diffs
      issues: write        # To respond to issue comments

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install --save-dev @types/node tsx

      - name: Run Code Review
        run: |
          npx tsx .github/scripts/pr-code-review.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}