name: Set PR Details

on:
  pull_request:
    types: [opened]

jobs:
  set-description:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR details
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const description = "This PR was automatically described by a workflow.esrsere";
            const title = "[DXQ-1234] PR Title Set by Workflow";
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              title,
              body: description
            });
