name: Test Comments

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test comment trigger
        run: |
          echo "Comment detected!"
          echo "Event: ${{ github.event_name }}"
          echo "Comment: ${{ github.event.comment.body }}"