name: Test Comments
on:
  issue_comment:
    types: [created]
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug event type
        run: |
          echo "Event name: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "Comment body: ${{ github.event.comment.body }}"
            echo "Issue number: ${{ github.event.issue.number }}"
            echo "Has PR: ${{ !!github.event.issue.pull_request }}"
          fi